version: "3.8"

services:
  Heliotrope:
    container_name: Heliotrope
    image: ghcr.io/saebasol/heliotrope:latest
    restart: always
    expose:
      - 8000
    networks:
      - saebasol

networks:
  saebasol:
    external: true
