version: "3.8"

services:
  mariadb:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    expose:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data/
      - ./preferences:/etc/postgresql.conf
    environment:
      POSTGRES_PASSWORD: "saebasol"
    networks:
      - saebasol

networks:
  saebasol:
    external: true
